Repository CCA-Public/scope, pull requests merged in 2018-09, with the labels that each got.

#109 Updating django.po - French translation round 2
  accesspoc/locale/fr/LC_MESSAGES/django.po
Labels: in progress

#104 Add Setting model and Dublin Core settings
  accesspoc/accesspoc/static/styles/_forms.scss
  accesspoc/accesspoc/static/styles/main.scss
  accesspoc/accesspoc/urls.py
  accesspoc/dips/forms.py
  accesspoc/dips/migrations/0013_setting.py
  accesspoc/dips/models.py
  accesspoc/dips/tests/test_dublin_core_settings.py
  accesspoc/dips/tests/test_user_access.py
  accesspoc/dips/views.py
  accesspoc/templates/includes/dc.html
  accesspoc/templates/includes/header.html
  accesspoc/templates/settings.html
  requirements/base.txt
Labels: enhancement, review

#108 Upgrade Django and other dependencies
  accesspoc/dips/migrations/0014_auto_20180910_1525.py
  accesspoc/dips/models.py
  accesspoc/dips/tests/test_DIP.py
  accesspoc/dips/tests/test_collection.py
  accesspoc/dips/tests/test_delete_by_dc_form.py
  accesspoc/dips/tests/test_dip_download.py
  accesspoc/dips/tests/test_home_collections_templates.py
  accesspoc/dips/tests/test_import_failure_display.py
  accesspoc/dips/tests/test_import_pending_redirect.py
  accesspoc/dips/tests/test_models_to_docs.py
  accesspoc/dips/tests/test_new_collection.py
  accesspoc/dips/tests/test_signal_handlers.py
  accesspoc/dips/tests/test_user_access.py
  accesspoc/dips/tests/test_user_groups.py
  accesspoc/search/documents.py
  accesspoc/search/management/commands/index_data.py
  requirements/base.txt
  requirements/test.txt
Labels: review

#112 Squash migrations
  accesspoc/dips/migrations/0001_initial.py
  accesspoc/dips/migrations/0002_add_user_group.py
  accesspoc/dips/migrations/0002_initial_data.py
  accesspoc/dips/migrations/0003_modify_user_groups.py
  accesspoc/dips/migrations/0004_auto_20180623_0114.py
  accesspoc/dips/migrations/0005_copy_dc_metadata.py
  accesspoc/dips/migrations/0006_fix_foreing_keys.py
  accesspoc/dips/migrations/0007_auto_20180623_0227.py
  accesspoc/dips/migrations/0008_auto_20180624_1652.py
  accesspoc/dips/migrations/0009_auto_20180721_1926.py
  accesspoc/dips/migrations/0010_add_viewers_user_group.py
  accesspoc/dips/migrations/0011_auto_20180729_1659.py
  accesspoc/dips/migrations/0012_taskresult.py
  accesspoc/dips/migrations/0013_setting.py
  accesspoc/dips/migrations/0014_auto_20180910_1525.py
Labels: review
