Repository CCA-Public/scope, pull requests merged in 2018-08, with the labels that each got.

#77 Omit tests from code coverage
  .coveragerc
Labels: enhancement, review

#81 Adding French translation to django.po
  accesspoc/locale/fr/LC_MESSAGES/django.po
Labels: in progress

#80 Improve Django settings and install notes
  .gitignore
  README.md
  accesspoc/accesspoc/settings.py
  accesspoc/accesspoc/static/css/bootstrap.min.css
  accesspoc/accesspoc/static/css/custom.css
  accesspoc/accesspoc/static/fontawesome/css/fontawesome.css
  accesspoc/accesspoc/static/fontawesome/css/solid.css
  accesspoc/accesspoc/static/fontawesome/webfonts/fa-solid-900.eot
  accesspoc/accesspoc/static/fontawesome/webfonts/fa-solid-900.svg
  accesspoc/accesspoc/static/fontawesome/webfonts/fa-solid-900.ttf
  accesspoc/accesspoc/static/fontawesome/webfonts/fa-solid-900.woff
  accesspoc/accesspoc/static/fontawesome/webfonts/fa-solid-900.woff2
  accesspoc/accesspoc/static/js/bootstrap.min.js
  accesspoc/accesspoc/static/js/custom.js
  accesspoc/accesspoc/static/js/jquery-3.2.1.min.js
  accesspoc/accesspoc/static/js/popper.min.js
  accesspoc/accesspoc/urls.py
  accesspoc/dips/tests/test_dip_download.py
  accesspoc/dips/tests/test_user_access.py
  accesspoc/dips/views.py
  accesspoc/templates/dip.html
  docker-compose.yml
  etc/nginx/nginx.conf
  tox.ini
Labels: review

#84 Collapse preservation metadata section
  accesspoc/templates/digitalfile.html
Labels: review

#103 Improve layout and style
  accesspoc/accesspoc/static/styles/_variables.scss
  accesspoc/locale/en/LC_MESSAGES/django.po
  accesspoc/locale/fr/LC_MESSAGES/django.po
  accesspoc/templates/digitalfile.html
  accesspoc/templates/home.html
  accesspoc/templates/login.html
Labels: review
