Repository CCA-Public/scope, pull requests merged in 2018-07, with the labels that each got.

#51 Feature file feedback
  features/async_processes.feature
  features/data_tables.feature
  features/dublin_core_settings.feature
  features/elasticsearch.feature
  features/user_management_and_permissions.feature
  features/zip_files_storage.feature
Labels: in progress

#57 Changes in data tables
  accesspoc/dips/templatetags/custom_tags.py
  accesspoc/dips/tests/test_DIP.py
  accesspoc/dips/tests/test_collection.py
  accesspoc/dips/tests/test_home.py
  accesspoc/dips/tests/test_user_access.py
  accesspoc/dips/views.py
  accesspoc/search/documents.py
  accesspoc/static/css/custom.css
  accesspoc/static/css/datatables.min.css
  accesspoc/static/fontawesome/css/fontawesome.css
  accesspoc/static/fontawesome/css/solid.css
  accesspoc/static/fontawesome/webfonts/fa-solid-900.eot
  accesspoc/static/fontawesome/webfonts/fa-solid-900.svg
  accesspoc/static/fontawesome/webfonts/fa-solid-900.ttf
  accesspoc/static/fontawesome/webfonts/fa-solid-900.woff
  accesspoc/static/fontawesome/webfonts/fa-solid-900.woff2
  accesspoc/static/js/datatables.min.js
  accesspoc/static/js/sorttable.js
  accesspoc/templates/base.html
  accesspoc/templates/collection.html
  accesspoc/templates/dip.html
  accesspoc/templates/home.html
  accesspoc/templates/includes/table_form.html
  accesspoc/templates/includes/table_header.html
  accesspoc/templates/includes/table_pager.html
  accesspoc/templates/login.html
  accesspoc/templates/search.html
  accesspoc/templates/users.html
Labels: review

#58 Setup Django i18n
  .gitignore
  Dockerfile
  README.md
  accesspoc/accesspoc/settings.py
  accesspoc/accesspoc/urls.py
  accesspoc/dips/forms.py
  accesspoc/dips/models.py
  accesspoc/dips/views.py
  accesspoc/locale/en/LC_MESSAGES/django.po
  accesspoc/locale/fr/LC_MESSAGES/django.po
  accesspoc/static/css/custom.css
  accesspoc/templates/base.html
  accesspoc/templates/collection.html
  accesspoc/templates/delete_collection.html
  accesspoc/templates/delete_dip.html
  accesspoc/templates/digitalfile.html
  accesspoc/templates/dip.html
  accesspoc/templates/edit_collection.html
  accesspoc/templates/edit_dip.html
  accesspoc/templates/edit_user.html
  accesspoc/templates/faq.html
  accesspoc/templates/home.html
  accesspoc/templates/includes/dc.html
  accesspoc/templates/includes/table_form.html
  accesspoc/templates/includes/table_header.html
  accesspoc/templates/includes/table_pager.html
  accesspoc/templates/login.html
  accesspoc/templates/new_collection.html
  accesspoc/templates/new_department.html
  accesspoc/templates/new_dip.html
  accesspoc/templates/new_user.html
  accesspoc/templates/search.html
  accesspoc/templates/users.html
Labels: demo2, review

#66 Add missing migration from i18n setup
  accesspoc/dips/migrations/0009_auto_20180721_1926.py
Labels: in progress, review

#68 Improve user groups management
  accesspoc/accesspoc/settings.py
  accesspoc/dips/migrations/0010_add_viewers_user_group.py
  accesspoc/dips/models.py
  accesspoc/dips/tests/test_get_users.py
  accesspoc/dips/tests/test_user_access.py
  accesspoc/dips/views.py
  accesspoc/templates/users.html
Labels: in progress, review

#71 Submit language form on language link click
  accesspoc/static/js/custom.js
  accesspoc/templates/base.html
Labels: review
